language: node_js
node_js:
  - "5"
before_script:
  - npm install grunt-cli -g
env:
  - CXX=g++-4.8  
# https://github.com/okTurtles/group-income-simple/issues/58
branches:
  only: 
    - master
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
